import type { Metadata } from "next";
// Using Google Fonts as an alternative due to @vercel/geist installation issue
import { Inter, Roboto_Mono } from "next/font/google";

import "./globals.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer';

// Initialize Inter and Roboto_Mono with their respective variables
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans", // Using a new variable name for clarity
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono", // Using a new variable name for clarity
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Apply the new font variables as CSS classes to the body
        className={`${inter.variable} ${roboto_mono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
